.\" Manpage for cupubot-bash.
.\" Contact epsi.nurwijayadi@gmail.com to correct errors or typos.
.TH man 1 "29 Jan 2018" "v0.001" "cupubot.bash man page"
.SH NAME
cupubot-bash \- a telegram bot in bash
.SH SYNOPSIS
cupubot-bash [options]
.SH DESCRIPTION
Cupubot is a telegram bot for learning purpose, or lame people. Just another learning project.
.SH OPTIONS
The cupubot-bash takes exactly one option.
.TP
\fB\-h\fR, \fB\-\-help\fR
display help information
.TP
\fB\-v\fR, \fB\-\-version\fR, \fBversion\fR
display version information
.TP
\fB\-\-observe\fR
show JSON output of getUpdates
.TP
\fB\-\-reply\fR
reply all messages
.TP
\fB\-\-new-member\fR
greet new member
.TP
\fB\-\-logger-text\fR
log chat conversation
.TP
\fB\-\-logger-html\fR
log chat conversation
.SH SEE ALSO
jq(1), json_reformat(1)
.SH BUGS
No known bugs.
.SH AUTHOR
E. Rizqi N. Sayidina (vivek@nixcraft.net.in)
